### GET request to example server
POST http://localhost:8080/api/v1/category/save-category
Content-Type: application/json

{
  "id": 1,
  "name": "",
  "description": "This is C++ Category",
  "isActive": true
}